name: Tests

on: [ push, pull_request ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [ 22.x, 24.x ]
        typescript-version: [ 5.5, 5.8, 5.9 ]

    steps:
      - name: Using branch ${{ github.ref }} for repository ${{ github.repository }}.
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install specific TS
        run: npm i -g typescript@${{ matrix.typescript-version }}

      - name: Check TypeScript version
        run: tsc --version

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: .yarn
          key: ${{ runner.OS }}-node-${{ matrix.node-version }}-typescript-${{ matrix.typescript-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-${{ matrix.node-version }}-typescript-${{ matrix.typescript-version }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Checking for peer dependency conflicts
        run: yarn check:peer-deps:fix

      - name: Run type tests
        run: yarn test:types
